#!/bin/bash
packagetype="branch"
packageurl="https://github.com/HansKristian-Work/vkd3d-proton"
packagearg="--recursive"
packageinstall() {
    if [[ -d "dlls" ]]; then rm -rf dlls; fi
    ./package-release.sh master dlls --no-package
}
export packagetype
export packageurl
export packagearg
export -f packageinstall
