#!/bin/bash
packagetype="branch"
packageurl="https://github.com/Frogging-Family/wine-tkg-git"
packageinstall() {
    cd wine-tkg-git || exit
    sh non-makepkg-build.sh
    if [[ -f "$PWD/non-makepkg-builds" ]]; then echo -e "\n\e[32mRunnner location:\e[0m $PWD/non-makepkg-builds"; fi
}
export packagetype
export packageurl
export -f packageinstall
