#!/bin/bash
packagetype="branch"
packageurl="https://github.com/daniruiz/flat-remix-gtk"
packageinstall() {
	if [[ ! -f "/usr/share/themes/.flat-remix-gtk" ]]; then
		sudo mkdir -p "/usr/share/themes/.flat-remix-gtk"
	else sudo rm -rf "/usr/share/themes/.flat-remix-gtk"
		sudo find "/usr/share/themes/" -xtype l -delete; fi
	sudo cp -r "themes/Flat-Remix"* "/usr/share/themes/.flat-remix-gtk"
	sudo ln -s "/usr/share/themes/.flat-remix-gtk/"* "/usr/share/themes/"
}
packageuninstall() {
	sudo rm -rf "/usr/share/themes/.flat-remix-gtk/"
	sudo find "/usr/share/themes/" -xtype l -delete
}
export packagetype
export packageurl
export -f packageinstall
export -f packageuninstall
