#!/bin/bash
packagetype="branch"
packageurl="https://github.com/daniruiz/flat-remix-gnome"
packageinstall() {
	if [[ -d "/usr/share/themes/.flat-remix-gnome" ]]; then
		sudo rm -rf "/usr/share/themes/.flat-remix-gnome"
		sudo find "/usr/share/themes/" -xtype l -delete; fi
	sudo mkdir -p "/usr/share/themes/.flat-remix-gnome"
	sudo cp -r "themes/Flat-Remix"* "/usr/share/themes/.flat-remix-gnome"
  sudo ln -s "/usr/share/themes/.flat-remix-gnome/"* "/usr/share/themes/"
}
packageuninstall() {
	sudo rm -rf "/usr/share/themes/.flat-remix-gnome/"
	sudo find "/usr/share/themes/" -xtype l -delete
}
export packagetype
export packageurl
export -f packageinstall
export -f packageuninstall
