#!/bin/bash
packagetype="branch"
packageurl="https://github.com/daniruiz/skeuos-gtk"
packageinstall() {
	sudo cp -r themes /usr/share
}
packageuninstall() {
	sudo rm -rf "/usr/share/themes/Skeuos"*
}
export packagetype
export packageurl
export -f packageinstall
export -f packageuninstall
