#!/bin/bash
packagetype="branch"
packageurl="https://github.com/vinceliuice/vimix-gtk-themes"
packageinstall() {
	sudo sh install.sh
}
packageuninstall() {
	sudo rm -rf "/usr/share/themes/vimix"*
}
export packagetype
export packageurl
export -f packageinstall
export -f packageuninstall
