#!/bin/bash
packagetype="branch"
packageurl="https://github.com/Frogging-Family/nvidia-all.git"
packageinstall() {
    makepkg -si
    sudo mkinitcpio -P
}
export packagetype
export packageurl
export -f packageinstall
