#!/bin/bash
packagetype="branch"
packageurl="https://github.com/citra-emu/citra"
packagearg="--recursive"
packageinstall() {
    if [[ ! -d "build" ]]; then mkdir build; fi
    cd build || exit; cmake ../ && make
    if [[ -f "$PWD/bin/Release/citra" ]]; then echo -e "\n\e[32mExecutable location:\e[0m $PWD/bin/Release/citra"; fi
}
export packagetype
export packageurl
export packagearg
export -f packageinstall
