#!/bin/bash
packagetype="release"
packagename="PCSX2/pcsx2"
packagever=".AppImage"
packageinstall() {
	if [[ -f "Pcsx2.AppImage" ]]; then rm "Pcsx2.AppImage"; fi
	mv pcsx2* Pcsx2.AppImage
	chmod +x Pcsx2.AppImage
	if [[ -f "$PWD/Pcsx2.AppImage" ]]; then echo -e "\n\e[32mExecutable location:\e[0m $PWD/Pcsx2.AppImage"; fi
}
export packagetype
export packagename
export packagever
export -f packageinstall
