#!/bin/bash
packagetype="branch"
packageurl="https://github.com/RPCS3/rpcs3"
packageinstall() {
    git submodule update --init; cd ..
    if [[ ! -d "rpcs3_build" ]]; then mkdir rpcs3_build; fi
    cd rpcs3_build || exit; cmake ../rpcs3/ && make
    if [[ -f "$PWD/bin/rpcs3" ]]; then echo -e "\n\e[32mExecutable location:\e[0m $PWD/bin/rpcs3"; fi
}
export packagetype
export packageurl
export -f packageinstall
