#!/bin/bash
packagetype="branch"
packageurl="https://github.com/Ryujinx/Ryujinx"
packageinstall() {
    dotnet publish -c Release
    if [[ -f "$PWD/Ryujinx/bin/Release/net5.0/Ryujinx" ]]; then echo -e "\n\e[32mExecutable location:\e[0m $PWD/Ryujinx/bin/Release/net5.0/Ryujinx"; fi
}
export packagetype
export packageurl
export -f packageinstall
