#!/bin/bash
packagetype="branch"
packageurl="https://github.com/mborgerson/xemu"
packageinstall() {
    ./build.sh
    if [[ -f "$PWD/dist/xemu" ]]; then echo -e "\n\e[32mExecutable location:\e[0m $PWD/dist/xemu"; fi
}
export packagetype
export packageurl
export -f packageinstall
