#!/bin/bash
packagetype="branch"
packageurl="https://gitlab.com/torkel104/libstrangle"
packageinstall() {
    make
    sudo make install
}

packageuninstall() {
    sudo make uninstall
}
export packagetype
export packageurl
export -f packageinstall
export -f packageuninstall
