#!/bin/bash
source "$HOME/Hist/Configs/vars"
source "$CONFPATH/main"
source "$CONFPATH/selector"
source "$CONFPATH/launchers"
source "$CONFPATH/wine"
source "$CONFPATH/steam"
source "$CONFPATH/packages"
steamfinder

listoptions "Hist Linux Utilities" "Launchers Creator|Wine Helper|Steam Helper|Packages Installer"
case $select_ans in
"1") #Launcher Creator
	ls $LAUNCHPATH > "$TEMPPATH/.launchers"
	while read line; do
		if [[ -z "$hi_launchers" ]]; then hi_launchers="$line"
		else hi_launchers="$hi_launchers|$line"; fi; done < "$TEMPPATH/.launchers"
	listoptions "Launchers Creator" "Create launcher|Edit launcher|Delete launcher|Open launcher in text editor|Run launcher"
		if [[ "$select_ans" == "1" ]]; then
			listoptions "Launcher Creator" "Wine App|Linux App"
			if [[ "$select_ans" == "1" ]]; then
				launchercreator "wine"
			elif [[ "$select_ans" == "2" ]]; then
				launchercreator "linux"; fi
		elif [[ "$select_ans" == "2" ]]; then
			launchereditor
		elif [[ "$select_ans" == "3" ]]; then
			listoptions "Launchers" "$hi_launchers"
			if [[ -L "$LAUNCHPATH/${list_array[select_ans-1]}" ]]; then
				rm "$(readlink -f "$LAUNCHPATH/${list_array[select_ans-1]}")"; fi
			rm "$LAUNCHPATH/${list_array[select_ans-1]}"
		elif [[ "$select_ans" == "4" ]]; then
			listoptions "Launchers" "$hi_launchers"; xdg-open "$LAUNCHPATH/${list_array[select_ans-1]}"
		elif [[ "$select_ans" == "5" ]]; then
			listoptions "Launchers" "$hi_launchers"; "$LAUNCHPATH/${list_array[select_ans-1]}"; fi
;;
"2") #Wine Helper
	listoptions "Wine Utilities" "Prefix commands|Winetricks|Dxvk|Vkd3d|Install MF|Install MF-Cab|Install mfplat.dll|Prefixes manager|Runners manager|Reset default prefix"
	if [[ "$select_ans" == "1" ]]; then
		prefixcommands		
	elif [[ "$select_ans" == "2" ]]; then
		prefixinit; runnerinit
		inputhistory "$HISTORYPATH/.winetricks" "${cyc}winetricks arguments${noc}" "exit" "gui"
		if [[ "$input_ans" == "gui" ]]; then 
			WINEPREFIX="$selected_prefix" WINE="$selected_runner" winetricks; else WINEPREFIX="$selected_prefix" WINE="$selected_runner" winetricks $input_ans; fi
	elif [[ "$select_ans" == "3" ]]; then
		if [[ -d "$PACKPATH/dxvk" ]]; then
			listoptions "Options List" "Install|Uninstall"; 
			if [[ "$select_ans" == "1" ]]; then update_option="install"
			elif [[ "$select_ans" == "2" ]]; then update_option="uninstall"; fi
			prefixinit
			WINEPREFIX="$selected_prefix" "$PACKPATH/dxvk/dlls/dxvk-master/setup_dxvk.sh" $update_option
		else echo -e "\nInstall ${grc}Dxvk${noc} from ${grc}Packages Installer${noc}!"; fi
	elif [[ "$select_ans" == "4" ]]; then
		if [[ -d "$PACKPATH/vkd3d-proton" ]]; then
			listoptions "Options List" "Install|Uninstall"; 
			if [[ "$select_ans" == "1" ]]; then update_option="install"
			elif [[ "$select_ans" == "2" ]]; then update_option="uninstall"; fi
			prefixinit
			if [[ ! -f "$selected_prefix/drive_c/windows/system32/d3d12.dll" ]]; then touch "$selected_prefix/drive_c/windows/system32/d3d12.dll"
			elif [[ ! -f "$selected_prefix/drive_c/windows/syswow64/d3d12.dll" ]]; then touch "$selected_prefix/drive_c/windows/syswow64/d3d12.dll"; fi
			WINEPREFIX="$selected_prefix" "$PACKPATH/vkd3d-proton/dlls/vkd3d-proton-master/setup_vkd3d_proton.sh" $update_option
		else echo -e "\nInstall ${grc}Vkd3d${noc} from ${grc}Packages Installer${noc}!"; fi
	elif [[ "$select_ans" == "5" ]]; then
		if [[ -d "$PACKPATH/mf-install" ]]; then
			prefixinit
			WINEPREFIX="$selected_prefix" "$PACKPATH/mf-install/mf-install.sh"
		else echo -e "\nInstall ${grc}MF${noc} from ${grc}Packages Installer${noc}!"; fi
	elif [[ "$select_ans" == "6" ]]; then
		if [[ -d "$PACKPATH/mf-installcab" ]]; then
			prefixinit
			WINEPREFIX="$selected_prefix" "$PACKPATH/mf-installcab/install-mf-64.sh"
		else echo -e "\nInstall ${grc}MF-Cab${noc} from ${grc}Packages Installer${noc}!"; fi
	elif [[ "$select_ans" == "7" ]]; then
		if [[ -d "$PACKPATH/mf-installcab" ]]; then execinit "wine"; cp "$PACKPATH/mf-installcab/mfplat.dll" "$init_result_dir"
		else echo -e "\nInstall ${grc}MF-Cab${noc} from ${grc}Packages Installer${noc}!"; fi
	elif [[ $select_ans == "8"  ]]; then
		listoptions "Lists Manager" "Add prefix|Create prefix|Delete prefix"
		if [[ "$select_ans" == "1" ]]; then addlines "prefix" "dir" "" "tofile" "$CONFPATH/addpfx.cfg" "winepfx"
		elif [[ "$select_ans" == "2" ]]; then prefixcreator
		elif [[ "$select_ans" == "3" ]]; then deletelines "Prefixes" "$CONFPATH/addpfx.cfg" "line"; fi
	elif [[ $select_ans == "9"  ]]; then
		listoptions "Lists Manager" "Add runner|Delete runner"
		if [[ "$select_ans" == "1" ]]; then addlines "runner" "dir" "" "tofile" "$CONFPATH/addrun.cfg" "winerun"
		elif [[ "$select_ans" == "2" ]]; then deletelines "Runners" "$CONFPATH/addrun.cfg" "line"; fi
	elif [[ $select_ans == "10"  ]]; then
		listoptions "Are you sure?" "Yes|No"
		if [[ "$select_ans" == "1" ]]; then
			rm -rf "$HOME/.wine"; mkdir "$HOME/.wine"; runnerinit; pfx_runner="$init_result"; WINEPREFIX="$HOME/.wine" "$pfx_runner" wineboot -u; fi; fi
;;
"3") #Steam Helper
	listoptions "Steam Helper" "Set game launch options|Winetricks|Reset game prefix"
	if [[ $select_ans == "1" ]]; then steamlauchoptions
	elif [[ $select_ans == "2" ]]; then
		readfiles "Steam game prefixes" "$TEMPPATH/.steampfx" "lines" "ans"; selected_prefix="$file_line_dir"; runnerinit
		inputhistory "$HISTORYPATH/.winetricks" "${cyc}winetricks arguments${noc}" "exit" "gui"
		if [[ "$input_ans" == "gui" ]]; then 
			WINEPREFIX="$selected_prefix" WINE="$selected_runner" winetricks; else WINEPREFIX="$selected_prefix" WINE="$selected_runner" winetricks $input_ans; fi
	elif [[ $select_ans == "3" ]]; then deletelines "Steam Prefixes" "$TEMPPATH/.steampfx" "lines" "delete" "steam"; fi
;;
"4") #Packages Installer
	packsinstaller
esac
