#!/bin/bash
packagetype="branch"
packageurl="https://github.com/Frogging-Family/wine-tkg-git"
packageinstall() {
    cd proton-tkg || exit
    makepkg -si
}
export packagetype
export packageurl
export -f packageinstall
