#!/bin/bash
packagetype="branch"
packageurl="https://github.com/flightlessmango/MangoHud"
packageinstall() {
    ./build.sh build
    ./build.sh package
    ./build.sh install
}

packageuninstall() {
    ./build.sh uninstall
}
