#!/bin/bash
packagetype="branch"
packageurl="https://github.com/flightlessmango/MangoHud"
packageinstall() {
    ./build.sh build
    ./build.sh package
    ./build.sh install
}

packageuninstall() {
    ./build.sh uninstall
}
export packagetype
export packageurl
export -f packageinstall
export -f packageuninstall
