#!/bin/bash
packagetype="branch"
packageurl="https://github.com/DadSchoorse/vkBasalt"
packageinstall() {
    meson --buildtype=release --prefix=/usr builddir
    ninja -C builddir install
}

packageuninstall() {
    sudo ninja -C builddir uninstall
}
export packagetype
export packageurl
export -f packageinstall
export -f packageuninstall
